insert into products value {  "id": 1, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 2, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 3, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 4, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 5, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 6, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 1, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 1, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 1, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}
insert into products value {  "id": 1, "title": "Fishing Rod", "description": "Perfect rod from bambook", "price": 15}